name: CI

on:
  push:
    branches:
      - master
    tags: 
      - '*'
  pull_request: ~
  workflow_dispatch:

permissions:
  contents: write

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker://node:10-alpine
        name: Setup Node

      - name: Install dependencies
        working-directory: _tools
        run: npm install

      - name: Assemble and pack
        working-directory: _tools
        run: npx gulp

      - uses: actions/upload-artifact@v4
        with:
          name: PBO-Files
          path: _tools/build/pbo

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: PBO-Files
